from __future__ import annotations

from enum import Enum


class StringEnum(str, Enum):
    def __str__(self) -> str:
        return str(self.value)


class RunType(StringEnum):
    SUPERVISOR_TURN = "SUPERVISOR_TURN"
    PROFILE_DETECTION = "PROFILE_DETECTION"
    FULL_EXTRACTION = "FULL_EXTRACTION"
    SCOPED_CORRECTION = "SCOPED_CORRECTION"
    # Deprecated request value kept during migration to SCOPED_CORRECTION.
    SCOPED_REMEDIATION = "SCOPED_REMEDIATION"
    IMPROVEMENT_CANDIDATE = "IMPROVEMENT_CANDIDATE"
    PROFILE_EVALUATION = "PROFILE_EVALUATION"
    PROFILE_CANARY = "PROFILE_CANARY"


class RunStatus(StringEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_INPUT = "WAITING_INPUT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ScopeType(StringEnum):
    CONNECTION = "CONNECTION"
    DRAWING = "DRAWING"
    WORKSPACE = "WORKSPACE"
    PROJECT = "PROJECT"
    PROFILE = "PROFILE"


class AgentStage(StringEnum):
    PROFILE_DETECTION = "PROFILE_DETECTION"
    RENDER = "RENDER"
    PAGE_CLASSIFICATION = "PAGE_CLASSIFICATION"
    PAGE_SCAN = "PAGE_SCAN"
    BUILD_CROSS_PAGE_TASKS = "BUILD_CROSS_PAGE_TASKS"
    CROSS_PAGE_COMPLETION = "CROSS_PAGE_COMPLETION"
    VALIDATION = "VALIDATION"
    PROPOSAL = "PROPOSAL"
    FEEDBACK_TRIAGE = "FEEDBACK_TRIAGE"
    ISSUE_DIAGNOSIS = "ISSUE_DIAGNOSIS"
    REMEDIATION_PLANNING = "REMEDIATION_PLANNING"
    EVALUATION = "EVALUATION"


class ProfileStatus(StringEnum):
    ACTIVE = "active"
    EXPERIMENTAL = "experimental"
    RETIRED = "retired"


class ProfileDetectionStatus(StringEnum):
    PROFILE_SELECTED = "PROFILE_SELECTED"
    WAITING_INPUT = "WAITING_INPUT"


class ErrorCode(StringEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED_SERVICE = "UNAUTHORIZED_SERVICE"
    PROJECT_CONTEXT_NOT_FOUND = "PROJECT_CONTEXT_NOT_FOUND"
    PROFILE_NOT_CONFIRMED = "PROFILE_NOT_CONFIRMED"
    PROFILE_VERSION_NOT_FOUND = "PROFILE_VERSION_NOT_FOUND"
    SOURCE_ARTIFACT_EXPIRED = "SOURCE_ARTIFACT_EXPIRED"
    MODEL_TEMPORARILY_UNAVAILABLE = "MODEL_TEMPORARILY_UNAVAILABLE"
    MODEL_SCHEMA_INVALID = "MODEL_SCHEMA_INVALID"
    CHECKPOINT_CONFLICT = "CHECKPOINT_CONFLICT"
    BASE_VERSION_CONFLICT = "BASE_VERSION_CONFLICT"
    RUN_ALREADY_ACTIVE = "RUN_ALREADY_ACTIVE"
    RUN_CANCELLED = "RUN_CANCELLED"
    EVALUATION_FAILED = "EVALUATION_FAILED"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    PROFILE_INVALID = "PROFILE_INVALID"
    PERSISTENCE_UNAVAILABLE = "PERSISTENCE_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class EventType(StringEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_STARTED = "RUN_STARTED"
    PROFILE_DETECTED = "PROFILE_DETECTED"
    PROFILE_REVIEW_REQUIRED = "PROFILE_REVIEW_REQUIRED"
    STAGE_STARTED = "STAGE_STARTED"
    ITEM_COMPLETED = "ITEM_COMPLETED"
    STAGE_COMPLETED = "STAGE_COMPLETED"
    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    HUMAN_INPUT_REQUIRED = "HUMAN_INPUT_REQUIRED"
    RUN_FAILED = "RUN_FAILED"
    RUN_CANCELLED = "RUN_CANCELLED"
    RUN_COMPLETED = "RUN_COMPLETED"


class RootCauseCategory(StringEnum):
    PROFILE_ROUTING_ERROR = "PROFILE_ROUTING_ERROR"
    PAGE_CLASSIFICATION_ERROR = "PAGE_CLASSIFICATION_ERROR"
    MODEL_PERCEPTION_ERROR = "MODEL_PERCEPTION_ERROR"
    PROMPT_RULE_GAP = "PROMPT_RULE_GAP"
    CROSS_PAGE_RESOLUTION_ERROR = "CROSS_PAGE_RESOLUTION_ERROR"
    DETERMINISTIC_RULE_ERROR = "DETERMINISTIC_RULE_ERROR"
    SCHEMA_MAPPING_ERROR = "SCHEMA_MAPPING_ERROR"
    SOURCE_INSUFFICIENT = "SOURCE_INSUFFICIENT"
    USER_EXPECTATION_MISMATCH = "USER_EXPECTATION_MISMATCH"
    TRANSIENT_MODEL_ERROR = "TRANSIENT_MODEL_ERROR"


class SupervisorIntent(StringEnum):
    DETECT_PROFILE = "DETECT_PROFILE"
    QUERY_CONTEXT = "QUERY_CONTEXT"
    PROCESS_DOCUMENT = "PROCESS_DOCUMENT"
    CORRECT_RESULT = "CORRECT_RESULT"
    QUERY_STATUS = "QUERY_STATUS"
    VIEW_RULES = "VIEW_RULES"
    CONFIRM_INPUT = "CONFIRM_INPUT"
    CONFIRM_RESULT_PATCH = "CONFIRM_RESULT_PATCH"
    AUTHORIZE_PROFILE_CANDIDATE = "AUTHORIZE_PROFILE_CANDIDATE"
    UNKNOWN = "UNKNOWN"


class SupervisorTurnStatus(StringEnum):
    WAITING_INPUT = "WAITING_INPUT"
    DISPATCHED = "DISPATCHED"
    ANSWERED = "ANSWERED"
    REJECTED = "REJECTED"


class WorkflowKind(StringEnum):
    PROFILE_DETECTION = "PROFILE_DETECTION"
    EXTRACTION = "EXTRACTION"
    CORRECTION = "CORRECTION"
    IMPROVEMENT = "IMPROVEMENT"
    READ_ONLY_QUERY = "READ_ONLY_QUERY"
    RESUME_WAITING_RUN = "RESUME_WAITING_RUN"


class CorrectionAction(StringEnum):
    DIRECT_PATCH = "DIRECT_PATCH"
    RERUN_STAGE_1 = "RERUN_STAGE_1"
    RERUN_STAGE_2 = "RERUN_STAGE_2"
    RERUN_STAGE_2_AND_3 = "RERUN_STAGE_2_AND_3"
    DETERMINISTIC_ONLY = "DETERMINISTIC_ONLY"
    NO_ACTION = "NO_ACTION"


class CorrectionIssueKind(StringEnum):
    DIRECT_VALUE_CHANGE = "DIRECT_VALUE_CHANGE"
    RECOGNITION_ERROR = "RECOGNITION_ERROR"
    MISSING_START = "MISSING_START"
    PAGE_CLASSIFICATION_ERROR = "PAGE_CLASSIFICATION_ERROR"
    FORMAT_OR_ORDER = "FORMAT_OR_ORDER"
    SOURCE_INSUFFICIENT = "SOURCE_INSUFFICIENT"


class CrossPageState(StringEnum):
    SAME_PAGE = "same_page"
    CROSS_PAGE = "cross_page"
    UNKNOWN = "unknown"


class EvalCaseKind(StringEnum):
    TARGET = "target"
    PROTECTED = "protected"
    NEGATIVE = "negative"
    EDGE = "edge"
    SHADOW = "shadow"


class ProfileCandidateType(StringEnum):
    PROMPT_PATCH = "PROMPT_PATCH"
    FEW_SHOT_ADD_OR_REPLACE = "FEW_SHOT_ADD_OR_REPLACE"
    SCHEMA_PATCH = "SCHEMA_PATCH"
    PROFILE_SIGNATURE_PATCH = "PROFILE_SIGNATURE_PATCH"
    REFERENCE_RESOLVER_PATCH = "REFERENCE_RESOLVER_PATCH"
    NORMALIZER_PATCH = "NORMALIZER_PATCH"
    VALIDATOR_PATCH = "VALIDATOR_PATCH"
    MODEL_CONFIG_PATCH = "MODEL_CONFIG_PATCH"


class ProfileCandidateStatus(StringEnum):
    DRAFT = "DRAFT"
    EVALUATING = "EVALUATING"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    CANARY = "CANARY"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    ROLLED_BACK = "ROLLED_BACK"


class EvaluationRecommendation(StringEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
